aiven/aiven-operator

- Makefile
Neither of these two commands was not generating anything, fixing a path
> fix makefile generate and manifest commands

- docs/content/en/docs/resources/kafka/_index.md
Signed-off-by: Lukáš Vlček <lukas.vlcek@aiven.io>
> Fix Kafka links

- CHANGELOG.md
- controllers/clickhouseuser_controller.go
- controllers/common.go
- controllers/controller.go
- controllers/kafkaacl_controller.go
- controllers/kafkaacl_controller_test.go
- controllers/suite_test.go
- go.mod
Fix KafkaACL not deleted on Aiven side.
> fix KafkaACL deletion

- controllers/common.go
Proxy client version to the user agent. Resolves #196
> fix aiven client useragent

- .github/workflows/acceptance-tests.yaml
Enables manual test run button.
> let run acc tests on demand

- .github/workflows/acceptance-tests.yaml
> fix run acc tests on demand

- CHANGELOG.md
> release: v0.6.0

- CHANGELOG.md
- controllers/kafkaacl_controller.go
- controllers/kafkaacl_controller_test.go
Recreates Kafka ACL if it's been modified.
> fix kafka acl lifecycle

- userconfigs_generator/generator.go
Validates input service list being generated as expected
> validate generated service list

- .github/workflows/acceptance-tests-ignore.yaml
- .github/workflows/acceptance-tests.yaml
Run acc for go file change only
> run acc for go file change only

- CHANGELOG.md
> release: v0.7.0

- CHANGELOG.md
- api/v1alpha1/mysql_webhook.go
- config/webhook/manifests.yaml
> fix MySQL webhook name

- api/v1alpha1/cassandra_webhook.go
- api/v1alpha1/grafana_webhook.go
- config/webhook/manifests.yaml
> fix cassandra and grafana webhooks

- api/v1alpha1/cassandra_webhook.go
- api/v1alpha1/grafana_webhook.go
- config/webhook/manifests.yaml
Fixes cassandra and grafana endpoints
> fix webhooks endpoints

- config/samples/aiven.io_v1alpha1_clickhouse.yaml
- config/samples/aiven.io_v1alpha1_opensearch.yaml
- docs/content/en/docs/resources/opensearch/_index.md
- test/e2e/opensearch/opensearch-simple-cluster/01-opensearch.yaml
- test/e2e/projectvpc/projectvpc-ref/01-resources.yaml
Add documentation for OpenSearch resource.
> Add OpenSearch resource to docs

- docs/content/en/docs/resources/redis/_index.md
Add documentation for working with Redis.
> Add Redis resource to docs

- api/v1alpha1/mysql_webhook.go
- config/webhook/manifests.yaml
> fix mysql webhook

- CHANGELOG.md
> release: v0.7.1

- .github/workflows/acceptance-tests.yaml
- Makefile
> ci(tests): separate job per each package

- controllers/controller.go
When a resource was successfully created, and after that, a token expires or becomes invalid, error handling is supposed to pass such cases and successfully finalize the resource and remove it from k8s.
> fix: unable to remove resources with invalid token

- .github/workflows/release.yaml
- Makefile
- Uses extended hugo version
- Bump up hugo version
- Bump up docsy submodule to resolve deprecations (mostly)
> fix docs release

- .github/workflows/pages.yaml
- .github/workflows/release.yaml
- Makefile
- use docsy compatible version
- fix docs static generation
> fix docs static generation, downgrade docsy

- api/v1alpha1/userconfigs/cassandra/cassandra.go
- api/v1alpha1/userconfigs/clickhouse/clickhouse.go
- api/v1alpha1/userconfigs/grafana/grafana.go
- api/v1alpha1/userconfigs/kafka/kafka.go
- api/v1alpha1/userconfigs/kafka_connect/kafka_connect.go
- api/v1alpha1/userconfigs/mysql/mysql.go
- api/v1alpha1/userconfigs/opensearch/opensearch.go
- api/v1alpha1/userconfigs/pg/pg.go
- api/v1alpha1/userconfigs/redis/redis.go
- config/crd/bases/aiven.io_cassandras.yaml
- config/crd/bases/aiven.io_clickhouses.yaml
- config/crd/bases/aiven.io_grafanas.yaml
- config/crd/bases/aiven.io_kafkaconnects.yaml
- config/crd/bases/aiven.io_kafkas.yaml
- config/crd/bases/aiven.io_mysqls.yaml
- config/crd/bases/aiven.io_opensearches.yaml
- config/crd/bases/aiven.io_postgresqls.yaml
- config/crd/bases/aiven.io_redis.yaml
- userconfigs_generator/generator.go
- userconfigs_generator/pg/pg.go
Otherwise, field names become as a part of manifest/docs description.
> remove field name from comment

- .github/workflows/release.yaml
- Dockerfile
Fixes #264
Note that I have not tested the GH actions workflow.
> Building arm64 image

- CHANGELOG.md
- api/v1alpha1/userconfigs/cassandra/cassandra.go
- api/v1alpha1/userconfigs/kafka/kafka.go
- api/v1alpha1/userconfigs/pg/pg.go
- config/crd/bases/aiven.io_cassandras.yaml
- config/crd/bases/aiven.io_kafkas.yaml
- config/crd/bases/aiven.io_postgresqls.yaml
- go.mod
- go.sum
Retry connection and some 5XX errors
> build(deps): use retryable http client

- CHANGELOG.md
- docs/docs/changelog.md
- docs/docs/installation/helm.md
- Adds missing entry to the changelog
- Separates input and output in installation instructions
> docs(installation): add hints and code blocks

- docs/mkdocs.yml
- Fix `HH:mm:ss` is rendered as an emoji
- Fix docs url
> docs(gen): disable emoji

- api/v1alpha1/common.go
- config/crd/bases/aiven.io_cassandras.yaml
- config/crd/bases/aiven.io_clickhouses.yaml
- config/crd/bases/aiven.io_grafanas.yaml
- config/crd/bases/aiven.io_kafkaconnects.yaml
- config/crd/bases/aiven.io_kafkas.yaml
- config/crd/bases/aiven.io_mysqls.yaml
- config/crd/bases/aiven.io_opensearches.yaml
- config/crd/bases/aiven.io_postgresqls.yaml
- config/crd/bases/aiven.io_redis.yaml
- docs/docs/api-reference/cassandra.md
- docs/docs/api-reference/clickhouse.md
- docs/docs/api-reference/grafana.md
- docs/docs/api-reference/kafka.md
- docs/docs/api-reference/kafkaconnect.md
- docs/docs/api-reference/mysql.md
- docs/docs/api-reference/opensearch.md
- docs/docs/api-reference/postgresql.md
- docs/docs/api-reference/redis.md
Updates docs with `serviceIntegration` property description
> add serviceIntegration property doc

- docs/docs/api-reference/cassandra.md
- docs/docs/api-reference/clickhouse.md
- docs/docs/api-reference/clickhouseuser.md
- docs/docs/api-reference/connectionpool.md
- docs/docs/api-reference/database.md
- docs/docs/api-reference/grafana.md
- docs/docs/api-reference/kafka.md
- docs/docs/api-reference/kafkaacl.md
- docs/docs/api-reference/kafkaconnect.md
- docs/docs/api-reference/kafkaconnector.md
- docs/docs/api-reference/kafkaschema.md
- docs/docs/api-reference/kafkatopic.md
- docs/docs/api-reference/mysql.md
- docs/docs/api-reference/opensearch.md
- docs/docs/api-reference/postgresql.md
- docs/docs/api-reference/project.md
- docs/docs/api-reference/projectvpc.md
- docs/docs/api-reference/redis.md
- docs/docs/api-reference/serviceintegration.md
- docs/docs/api-reference/serviceuser.md
- docs_generator/main.go
> add links to parent schemas

- .github/workflows/tests.yaml
- CHANGELOG.md
- Makefile
- api/v1alpha1/kafkatopic_types.go
- config/crd/bases/aiven.io_kafkatopics.yaml
- controllers/kafkatopic_controller.go
- docs/docs/api-reference/examples/kafkatopic.yaml
- docs/docs/api-reference/kafkatopic.md
- tests/kafkatopic_test.go
- tests/suite_test.go
Adds `KafkaTopic.Spec.topicName` field.
> feat(kafkatopic): add topicName property

- test/e2e/kafka-connector/connect-kafka-to-postgres/05-delete.yaml
Removes kafka and kafka topic after the test
> chore(e2e): remove kafka after the test

- CHANGELOG.md
- api/v1alpha1/common.go
- config/crd/bases/aiven.io_cassandras.yaml
- config/crd/bases/aiven.io_clickhouses.yaml
- config/crd/bases/aiven.io_grafanas.yaml
- config/crd/bases/aiven.io_kafkaconnects.yaml
- config/crd/bases/aiven.io_kafkas.yaml
- config/crd/bases/aiven.io_mysqls.yaml
- config/crd/bases/aiven.io_opensearches.yaml
- config/crd/bases/aiven.io_postgresqls.yaml
- config/crd/bases/aiven.io_redis.yaml
- docs/docs/api-reference/cassandra.md
- docs/docs/api-reference/clickhouse.md
- docs/docs/api-reference/examples/kafka.yaml
- docs/docs/api-reference/grafana.md
- docs/docs/api-reference/kafka.md
- docs/docs/api-reference/kafkaconnect.md
- docs/docs/api-reference/mysql.md
- docs/docs/api-reference/opensearch.md
- docs/docs/api-reference/postgresql.md
- docs/docs/api-reference/redis.md
- docs_generator/validator.go
- test/e2e/kafka-topic/simple-kafka-topic/01-kafka.yaml
- test/e2e/kafka/kafka-simple-cluster/01-kafka.yaml
- Marks service plan field as required
- Fixes `disk_space` typo
> fix(service): mark plan as a required field

- .github/workflows/acceptance-tests.yaml
- controllers/clickhouse_controller_test.go
- tests/clickhouse_test.go
- tests/grafana_test.go
- tests/suite.go
- Adds test on the new suite
- Removes old one
> refactor(tests): test clickhouse with the new suite

- docs/docs/resources/postgresql.md
Add instructions for creating read-only replica to PG resource doc.
> docs(postgresql): add instructions for creating read-only replica

- CHANGELOG.md
- generators/charts/cluster_roles.go
Adds generation for the feature proposed in #332
> feat(charts): add rbac options to cluster_role.yaml generator

- CHANGELOG.md
- charts/aiven-operator/templates/cluster_role.yaml
- charts/aiven-operator/templates/cluster_role_binding.yaml
- generators/charts/cluster_roles.go
> revert(charts): add rbac options to helm chart

- charts/aiven-operator/values.yaml
> revert(charts): remove rbac options values

- .github/workflows/release.yaml
- Dockerfile
- controllers/basic_controller.go
- controllers/common.go
- controllers/suite_test.go
- tests/suite_test.go
> feat(client): add version build flag to the client user-agent

- .github/dependabot.yml
- .github/workflows/generate.yaml
- .github/workflows/lint.yaml
- .github/workflows/pages.yaml
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- .golangci.yml
fixes GitHub Actions YAML spec errors, also sets Go version to use `go.mod` everywhere
> ci: fix github actions yaml spec errors

- .github/sync.yml
- .github/workflows/release.yaml
adds charts sync CI job on release
> ci(release): add charts sync job

- CHANGELOG.md
- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- docs/docs/changelog.md
> chore(release): v0.11.0

- controllers/generic_service_handler.go
- tests/cassandra_test.go
- tests/clickhouse_test.go
- tests/grafana_test.go
- tests/kafka_test.go
- tests/mysql_test.go
- tests/opensearch_test.go
- tests/postgresql_test.go
- tests/redis_test.go
> feat: update service tags when creating or updating a service

- CHANGELOG.md
- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- docs/docs/changelog.md
> chore(release): v0.12.0

- .github/dependabot.yml
> ci(dependabot): ignore sigs.k8s.io/controller-runtime major/minor

- CHANGELOG.md
- controllers/kafka_controller.go
- tests/kafka_test.go
> fix(kafka): add missing sasl port

- CHANGELOG.md
- api/v1alpha1/kafka_types.go
- charts/aiven-operator-crds/templates/aiven.io_kafkas.yaml
- config/crd/bases/aiven.io_kafkas.yaml
- controllers/kafka_controller.go
- docs/docs/api-reference/kafka.md
- tests/kafka_test.go
> fix(kafka): expose schema registry port

- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- Add [TieredStorage](https://github.com/Aiven-Open/tiered-storage-for-apache-kafka) support to `Kafka`
- Add `Kafka` version `3.5`
- Add `Kafka` spec property `scheduled_rebalance_max_delay_ms`
- Mark deprecated `Kafka` spec property `remote_log_storage_system_enable`
- Add `KafkaConnect` spec property `scheduled_rebalance_max_delay_ms`
- Add `OpenSearch` spec property `openid` 
- Use updated go client with enhanced retries
> release: v0.13.0

- CHANGELOG.md
- api/v1alpha1/cassandra_webhook.go
- api/v1alpha1/clickhouse_webhook.go
- api/v1alpha1/common.go
- api/v1alpha1/grafana_webhook.go
- api/v1alpha1/kafka_webhook.go
- api/v1alpha1/kafkaconnect_webhook.go
- api/v1alpha1/mysql_webhook.go
- api/v1alpha1/opensearch_webhook.go
- api/v1alpha1/postgresql_webhook.go
- api/v1alpha1/redis_webhook.go
- tests/projectvpc_test.go
- tests/suite_test.go
User should be able to migrate service to different vpc.
> feat(vpc): make vpc id mutable

- CHANGELOG.md
- controllers/basic_controller.go
- controllers/common.go
- controllers/common_test.go
- controllers/generic_service_handler.go
- controllers/serviceintegration_controller.go
Fixes panic on empty user config marshal.
> fix(userconfig): empty config marshal panics

- controllers/basic_controller.go
> fix: return error from defer on object update

- .github/workflows/generate.yml
> ci: fix missing goimports

- controllers/basic_controller.go
- controllers/common.go
Adds an option for the user to chose if resources should be deleted on aiven-side.
Resolves https://github.com/aiven/aiven-operator/issues/510
> feat: add option to orphan resources

- CHANGELOG.md
- docs/docs/api-reference/cassandra.md
- docs/docs/api-reference/clickhouse.md
- docs/docs/api-reference/clickhouseuser.md
- docs/docs/api-reference/connectionpool.md
- docs/docs/api-reference/database.md
- docs/docs/api-reference/grafana.md
- docs/docs/api-reference/kafka.md
- docs/docs/api-reference/kafkaacl.md
- docs/docs/api-reference/kafkaconnect.md
- docs/docs/api-reference/kafkaconnector.md
- docs/docs/api-reference/kafkaschema.md
- docs/docs/api-reference/kafkatopic.md
- docs/docs/api-reference/mysql.md
- docs/docs/api-reference/opensearch.md
- docs/docs/api-reference/postgresql.md
- docs/docs/api-reference/projectvpc.md
- docs/docs/api-reference/redis.md
- docs/docs/api-reference/serviceintegration.md
- docs/docs/api-reference/serviceuser.md
- generators/docs/generator.go
Renders string format next to a string field in docs. Resolves #528
> feat(docs): add string format

- CHANGELOG.md
- docs/docs/contributing/resource-generation.md
- generators/charts/changelog.go
- generators/charts/changelog_test.go
- generators/charts/crds.go
- generators/charts/main.go
- generators/charts/version.go
> feat(release): CRD changelog generator

- Dockerfile
> fix(ci): use go1.21 in Dockerfile

- api/v1alpha1/common.go
controller-gen tries to generate CRD for interface type.
> fix: ignore interface generation

- CHANGELOG.md
- controllers/projectvpc_controller.go
Doesn't call DELETE vpc if it has running services.
> refactor(vpc): prevent vpc deletion with running services

- CHANGELOG.md
- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- docs/docs/changelog.md
Changes [v0.16.0...e6d9b3f9d529ecfffbcacc0ab411aeb54767ab87](https://github.com/aiven/aiven-operator/compare/v0.16.0...e6d9b3f9d529ecfffbcacc0ab411aeb54767ab87)
> chore(release): v0.16.1

- tests/serviceuser_test.go
Adds an extra test for service user.
> chore(serviceuser): add pg test

- CHANGELOG.md
- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- docs/docs/changelog.md
> chore(release): v0.17.0

- .trunk/trunk.yaml
- Dockerfile
- go.mod
- go.sum
Reverts aiven/aiven-operator#632
> Revert "chore: upgrade to go 1.22"

- .github/workflows/tests.yml
- Makefile
adds concurrency support to the tests that are run via CI
> ci(tests): concurrency support

- Makefile
- tests/session.go
Individual test timeouts was increased to 20 minutes (from 10) Overall test suite timeout was increated to 90 minutes (from 42)
> feat(tests): increase timeouts for tests

- CHANGELOG.md
- controllers/cassandra_controller.go
- controllers/clickhouse_controller.go
- controllers/generic_service_handler.go
- controllers/grafana_controller.go
- controllers/kafka_controller.go
- controllers/kafkaconnect_controller.go
- controllers/mysql_controller.go
- controllers/opensearch_controller.go
- controllers/postgresql_controller.go
- controllers/redis_controller.go
- tests/postgresql_test.go
> feat: check PG upgrade task before attempting to upgrade service

- CHANGELOG.md
- api/v1alpha1/database_types.go
- api/v1alpha1/database_webhook.go
- charts/aiven-operator-crds/templates/aiven.io_databases.yaml
- config/crd/bases/aiven.io_databases.yaml
- docs/docs/api-reference/database.md
- tests/database_test.go
Removes validation from the webhook.
> refactor(database): use crd validation rules

- controllers/cassandra_controller.go
- controllers/clickhouse_controller.go
- controllers/clickhouseuser_controller.go
- controllers/connectionpool_controller.go
- controllers/database_controller.go
- controllers/grafana_controller.go
- controllers/kafka_controller.go
- controllers/kafkaacl_controller.go
- controllers/kafkaconnect_controller.go
- controllers/kafkaconnector_controller.go
- controllers/kafkaschema_controller.go
- controllers/kafkatopic_controller.go
- controllers/mysql_controller.go
- controllers/opensearch_controller.go
- controllers/postgresql_controller.go
- controllers/project_controller.go
- controllers/projectvpc_controller.go
- controllers/redis_controller.go
- controllers/serviceintegration_controller.go
- controllers/serviceuser_controller.go
- controllers/setup.go
Builds reconcilers in a loop to reduce boilerplate.
> refactor: build reconcilers in a loop

- CHANGELOG.md
- api/v1alpha1/clickhousedatabase_types.go
- api/v1alpha1/database_types.go
- api/v1alpha1/kafkaacl_types.go
- api/v1alpha1/kafkaconnect_types.go
- api/v1alpha1/kafkaconnector_types.go
- api/v1alpha1/kafkaschema_types.go
- api/v1alpha1/kafkatopic_types.go
- api/v1alpha1/projectvpc_types.go
- api/v1alpha1/serviceintegration_types.go
> fix: no_secret is inverted

- CHANGELOG.md
- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- docs/docs/changelog.md
> chore(release): v0.18.0

- CHANGELOG.md
- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- docs/docs/changelog.md
Releases a fix for user agent version.
> chore(release): v0.18.1

- docs/docs/api-reference/examples/kafkaschemaregistryacl.yaml
- docs/docs/api-reference/kafkaschemaregistryacl.md
- docs/mkdocs.yml
Adds clickhousdatabase and kafkaschemaregistryacl to the docs.
> docs: add missing resources

- docs/docs/api-reference/examples/serviceintegrationendpoint.yaml
- docs/docs/api-reference/serviceintegrationendpoint.md
- docs/mkdocs.yml
Adds the docs page to the listing + manifest example.
> docs(serviceintegrationendpoint): add docs page and example

- CHANGELOG.md
- api/v1alpha1/redis_types.go
- charts/aiven-operator-crds/templates/aiven.io_redis.yaml
- config/crd/bases/aiven.io_redis.yaml
- controllers/generic_service_handler.go
- docs/docs/api-reference/redis.md
- tests/redis_test.go
The cert can't be used with this type of service.
> fix(redis): remove REDIS_CA_CERT secret key

- controllers/serviceintegration_controller.go
- controllers/serviceintegrationendpoint_controller.go
- sweeper/service_integrations.go
- sweeper/services.go
The gen client removed this function.
> fix: remove omitnotfound

- CHANGELOG.md
- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- docs/docs/changelog.md
~~Blocked by #746, lint action is broken currently.~~
v0.20.0
> chore(release): v0.20.0

- CHANGELOG.md
Reorder latest changelog entries
> docs: reorder latest changelog entries

- api/v1alpha1/clickhousegrant_types.go
- charts/aiven-operator-crds/templates/aiven.io_clickhousegrants.yaml
- config/crd/bases/aiven.io_clickhousegrants.yaml
- docs/docs/api-reference/clickhousedatabase.md
- docs/docs/api-reference/clickhousegrant.md
- docs/docs/api-reference/examples/clickhousegrant.yaml
* Document how existing privileges are handled and how new ones are added
* Add guidance to granting privilege on all tables in a database.
* Fix typo
> feat(clickhousegrant): improve docs

- controllers/clickhousedatabase_controller.go
- controllers/clickhousegrant_controller.go
- controllers/clickhouserole_controller.go
- controllers/clickhouseuser_controller.go
- controllers/connectionpool_controller.go
- controllers/database_controller.go
- controllers/generic_service_handler.go
- controllers/kafkaacl_controller.go
- controllers/kafkaconnector_controller.go
- controllers/kafkaschema_controller.go
- controllers/kafkaschemaregistryacl_controller.go
- controllers/kafkatopic_controller.go
- controllers/project_controller.go
- controllers/projectvpc_controller.go
- controllers/serviceintegration_controller.go
- controllers/serviceintegrationendpoint_controller.go
- controllers/serviceuser_controller.go
- docs/docs/resources/cassandra.md
- docs/docs/resources/mysql.md
- docs/docs/resources/opensearch.md
- docs/docs/resources/redis.md
* Fix typo in status condition message
* Remove "status remains unknown" from status condition message for instances for which the status is known after creation
> fix(controllers): update status condition messages

- CHANGELOG.md
- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- docs/docs/changelog.md
> chore(release): v0.21.0

- docs/docs/api-reference/cassandra.md
- docs/docs/api-reference/clickhouse.md
- docs/docs/api-reference/clickhousedatabase.md
- docs/docs/api-reference/clickhousegrant.md
- docs/docs/api-reference/clickhouserole.md
- docs/docs/api-reference/clickhouseuser.md
- docs/docs/api-reference/connectionpool.md
- docs/docs/api-reference/database.md
- docs/docs/api-reference/grafana.md
- docs/docs/api-reference/kafka.md
- docs/docs/api-reference/kafkaacl.md
- docs/docs/api-reference/kafkaconnect.md
- docs/docs/api-reference/kafkaschema.md
- docs/docs/api-reference/kafkaschemaregistryacl.md
- docs/docs/api-reference/kafkatopic.md
- docs/docs/api-reference/mysql.md
- docs/docs/api-reference/opensearch.md
- docs/docs/api-reference/postgresql.md
- docs/docs/api-reference/project.md
- docs/docs/api-reference/projectvpc.md
- docs/docs/api-reference/redis.md
- docs/docs/api-reference/serviceintegration.md
- docs/docs/api-reference/serviceintegrationendpoint.md
- docs/docs/api-reference/serviceuser.md
- generators/docs/generator.go
Generates example usage commands from examples.
Forms `kubectl get` output with true values.
> docs: generate usage commands

- Dockerfile
Fixes failed release workflow: https://github.com/aiven/aiven-operator/actions/runs/9661315516
> fix(dockerfile): copy utils/ to image

- docs/docs/resources/clickhouse.md
- docs/mkdocs.yml
Add example for creating a ClickHouse service, database, user and role.
> docs(clickhouse): add example

- README.md
- docs/docs/authentication.md
- docs/docs/contributing/developer-guide.md
- docs/docs/installation/helm.md
- docs/docs/installation/kubectl.md
- docs/docs/installation/uninstalling.md
- docs/docs/resources/cassandra.md
- docs/docs/resources/kafka/connect.md
- docs/docs/resources/kafka/index.md
- docs/docs/resources/kafka/schema.md
- docs/docs/resources/mysql.md
- docs/docs/resources/opensearch.md
- docs/docs/resources/postgresql.md
- docs/docs/resources/project-vpc.md
- docs/docs/resources/project.md
- docs/docs/resources/redis.md
- docs/docs/resources/service-integrations.md
- docs/docs/troubleshooting.md
Format headings and placeholders in code blocks to match style guide.
> docs: format headings and placeholders

- CHANGELOG.md
- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- docs/docs/changelog.md
- tests/clickhousegrant_test.go
> chore(release): v0.23.0

- controllers/clickhousedatabase_controller.go
- controllers/clickhousegrant_controller.go
- controllers/clickhouserole_controller.go
- controllers/clickhouseuser_controller.go
- controllers/common.go
- controllers/connectionpool_controller.go
- controllers/database_controller.go
- controllers/generic_service_handler.go
- controllers/kafkaacl_controller.go
- controllers/kafkaconnector_controller.go
- controllers/kafkaschema_controller.go
- controllers/kafkaschemaregistryacl_controller.go
- controllers/serviceintegration_controller.go
- controllers/serviceuser_controller.go
Renames `checkServiceIsRunning` to `checkServiceIsOperational`
> refactor: rename service running checker

- CHANGELOG.md
- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- docs/docs/changelog.md
- go.mod
- go.sum
> chore(release): v0.25.0

- charts/aiven-operator/templates/_helpers.tpl
- charts/aiven-operator/templates/cluster_role_binding.yaml
- charts/aiven-operator/templates/deployment.yaml
- charts/aiven-operator/templates/mutating_webhook_configuration.yaml
- charts/aiven-operator/templates/role_binding.yaml
- charts/aiven-operator/templates/validating_webhook_configuration.yaml
- charts/aiven-operator/values.yaml
- docs/docs/installation/helm.md
- generators/charts/webhooks.go
- main.go
- utils/utils.go
this PR addresses https://github.com/aiven/aiven-operator/issues/807
> feat: operator watched namespaces

- docs/docs/authentication.md
- docs/docs/index.md
- docs/docs/installation/helm.md
- docs/docs/installation/kubectl.md
- docs/docs/installation/prerequisites.md
- docs/docs/installation/uninstalling.md
- Update docs homepage and add links to examples
- Update installation instructions for clarity
> docs: update installation instructions and homepage

- CHANGELOG.md
- api/v1alpha1/valkey_webhook.go
- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- charts/aiven-operator/templates/cluster_role.yaml
- charts/aiven-operator/templates/mutating_webhook_configuration.yaml
- charts/aiven-operator/templates/validating_webhook_configuration.yaml
- config/rbac/role.yaml
- config/webhook/manifests.yaml
- controllers/valkey_controller.go
- docs/docs/api-reference/valkey.md
- docs/docs/changelog.md
- Refactors the valkey "resources" name
- Bumps up the charts version
> refactor(valkey): pluralize the "resources" name

- api/v1alpha1/redis_types.go
- charts/aiven-operator-crds/templates/aiven.io_redis.yaml
- config/crd/bases/aiven.io_redis.yaml
- docs/docs/api-reference/redis.md
- generators/docs/generator.go
- Adds deprecations support to the docs generator
- Deprecates `Redis`
> docs: support deprecation warnings

- CHANGELOG.md
- api/v1alpha1/redis_types.go
- charts/aiven-operator-crds/templates/aiven.io_redis.yaml
- config/crd/bases/aiven.io_redis.yaml
- docs/docs/api-reference/redis.md
- Adds the deprecation to the changelog
- Adds upgrade instructions link
> refactor(redis): add Redis to Valkey instructions link

- utils/alloydbomni/service_account_credentials_validator.go
- utils/alloydbomni/service_account_credentials_validator_test.go
Fixes `ValidateServiceAccountCredentials`.
> fix(alloydbomni): empty creds

- CHANGELOG.md
- api/v1alpha1/cassandra_types.go
- charts/aiven-operator-crds/templates/aiven.io_cassandras.yaml
- config/crd/bases/aiven.io_cassandras.yaml
- docs/docs/api-reference/cassandra.md
- docs/docs/resources/cassandra.md
Adds EOL notice to the Cassandra resource docs.
> docs(cassandra): add EOL notice

- CHANGELOG.md
- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- docs/docs/changelog.md
> chore(release): v0.28.0

- CHANGELOG.md
- controllers/serviceintegration_controller.go
- tests/connectionpool_test.go
Retry update operation in `service_integration` controller when API returns 404.
> feat(service_integration): added retry to update action

- .github/workflows/force-sync-charts.yml
- CHANGELOG.md
- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- docs/docs/changelog.md
> chore(release): v0.29.0

- Dockerfile
Sets go1.24 to the dockerfile.
> fix: dockerfile go version

- .github/workflows/release.yml
> fix(ci): rename old token var

- .github/workflows/tests.yml
- api/v1alpha1/project_types.go
- controllers/project_controller.go
- docs/docs/resources/examples/project.yaml
- docs/docs/resources/project.md
- tests/project_test.go
- tests/suite_test.go
> refactor(project): use generated client

- controllers/database_controller.go
- tests/database_test.go
Replaces the old client with generated.
Resolves NEX-1560.
> refactor(database): use gen client

- Taskfile.internal.yml
- controllers/clickhousedatabase_controller.go
- controllers/clickhouserole_controller.go
- controllers/clickhouseuser_controller.go
- controllers/project_controller.go
- go.mod
- go.sum
- tests/clickhouse_test.go
- tests/clickhouseuser_test.go
Resolves NEX-99.
Migrates:
- `ClickhouseDatabase`
- `ClickhouseRole`
- `ClickhouseUser`
> refactor(clickhouse): use gen client

- controllers/kafkaconnector_controller.go
- docs/docs/resources/examples/kafkaconnect.yaml
- docs/docs/resources/kafkaconnect.md
- go.mod
- go.sum
- tests/kafkaconnect_test.go
Resolves NEX-100.
- Uses the gen client
- Moves the test config to examples
> refactor(kafkaconnect): use gen client

- CHANGELOG.md
- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- docs/docs/changelog.md
> chore(release): v0.30.0

- CHANGELOG.md
- charts/aiven-operator/templates/hpa.yaml
Resolves: #968 
- upgraded deprecated HorizontalPodAutoscaler version
> chore(hpa): upgraded deprecated HorizontalPodAutoscaler version

- .github/workflows/slack-notify.yml
- .github/workflows/tests.yml
Resolves NEX-1688
- added slack notifications to the test job
> ci: added slack notifications to the test job

- docs/docs/troubleshooting.md
Contributes to #969 
- added reconciliation info to the troubleshooting section
> docs: added reconciliation info to the troubleshooting section

- controllers/kafkatopic_controller.go
Resolves #974  
- ~60 seconds for 250 topics
- singleflight deduplicate ~80% of the call, which still would be close to O(N), but significantly reduced globally with number of retries
> feat(kafkatopic): added concurrent reconcilers

- CHANGELOG.md
- charts/aiven-operator-crds/Chart.yaml
- charts/aiven-operator/Chart.yaml
- docs/docs/changelog.md
> chore(release): v0.31.0

- controllers/basic_controller.go
Resolves NEX-1706.
Client retries are sometimes not enough.
Let's the Kube retry the `createOrUpdate` operation.
> feat: retry 5xx errors on createOrUpdate

- charts/aiven-operator/templates/deployment.yaml
- charts/aiven-operator/values.yaml
- config/manager/manager.yaml
- main.go
Resolves: NEX-1700.
Contributes to #970 
- added customizable log levels for the customer
> feat: added customizable log levels

- gke/.env.example
- gke/.gitignore
- gke/Taskfile.yml
- gke/terraform/cluster/backend.tf
- gke/terraform/cluster/data.tf
- gke/terraform/cluster/main.tf
- gke/terraform/cluster/outputs.tf
- gke/terraform/cluster/providers.tf
- gke/terraform/cluster/variables.tf
This PR is just a first step for adding the testing setup for GKE cluster. In the following PRs the Aiven operator installation would be added with the required infra setup for that. For now this PR is limited only for K8S cluster on its own
- added Terraform for the GKE cluster setup
- added Taskfile for the orchestration
> feat: added test GKE cluster configuration

- gke/.env.example
- gke/Taskfile.yml
- gke/terraform/addons/backend.tf
- gke/terraform/addons/data.tf
- gke/terraform/addons/main.tf
- gke/terraform/addons/outputs.tf
- gke/terraform/addons/providers.tf
- gke/terraform/addons/variables.tf
- gke/terraform/cluster/main.tf
- gke/terraform/cluster/outputs.tf
- gke/terraform/cluster/variables.tf
Resolves: NEX-1747
- added Aiven operator installation to GKE with Taskfile commands for orchestration
The REAME guide and other sugar will be added in the next PR
> feat: added addon install on GKE cluster

- .trunk/trunk.yaml
- docs/docs/contributing/developer-guide.md
- gke/.gitignore
- gke/README.md
- gke/Taskfile.yml
- gke/terraform/addons/main.tf
- gke/test-resources/overlays/templates/README.md
- gke/test-resources/overlays/templates/kafka.yaml
- gke/test-resources/overlays/templates/kustomization.yaml
- gke/test-resources/overlays/templates/postgresql.yaml
Resolves: NEX-1775
- added resources deployment
> feat(gke): added resources deployment

- .github/workflows/tests.yml
-  enabled HTTP client debug logging on CI
> chore: enabled HTTP client debug logging on CI
