aiven/aiven-operator

api/v1alpha1/kafkaacl_webhook.go, config/rbac/role.yaml, controllers/kafkaacl_controller.go, controllers/kafkatopic_controller.go, test/e2e/kafka-topic/simple-kafka-topic/01-kafka-topic-acl.yaml, test/e2e/kafka-topic/simple-kafka-topic/02-check-services-running.yaml
This PR fixes the issue that we are not able to manage kafka ACLs right now because of missing RBACs for the status
=> fix missing kafka acl rbac

api/v1alpha1/kafka_types.go, api/v1alpha1/opensearch_types.go, api/v1alpha1/postgresql_types.go, config/crd/bases/aiven.io_kafkas.yaml, config/crd/bases/aiven.io_opensearches.yaml, config/crd/bases/aiven.io_postgresqls.yaml
We are not releasing K8s operator often these days and more important translation of user configuration options to K8s CRD's is mostly manual process and will be automated soon. This PR proposes to remove service version validation before we automate generation of user configuration options for K8s operator.
=> loosen service version validation

config/crd/bases/aiven.io_crd-all.gen.yaml, config/samples/aiven.io_v1alpha1_kafka.yaml
This PR fix a typo on the `disk_space` field in `config/samples/aiven.io_v1alpha1_kafka.yaml`
=> fix typo on config/samples/kafka disk_space

docs/content/en/docs/resources/postgresql/_index.md, docs/content/en/docs/resources/project-vpc/_index.md, docs/content/en/docs/resources/project/_index.md, docs/content/en/docs/resources/service-integrations/_index.md
Looks like this was fixed for the Kafka page but not for the other pages.
=> fix links for prerequisite notes

CHANGELOG.md, api/v1alpha1/common.go, config/crd/bases/aiven.io_clickhouses.yaml, config/crd/bases/aiven.io_kafkaconnects.yaml, config/crd/bases/aiven.io_kafkas.yaml, config/crd/bases/aiven.io_opensearches.yaml, config/crd/bases/aiven.io_postgresqls.yaml, config/crd/bases/aiven.io_redis.yaml
Removes "never" from choices of maintenance dow,
because it's not available in api.
=> remove "never" from dow choices

CHANGELOG.md, main.go
Adds `development` flag to configure logger. Resolves #210
=> add development flag to main.go

userconfigs_generator/generator.go, userconfigs_generator/generator_test.go, userconfigs_generator/generator_test_expected.go
Must be quoted if contains special characters. Otherwise, manifest generation fails with an error "extra arguments provided"
=> fix enum generation

docs/content/en/docs/resources/opensearch/_index.md
Removed the empty "Testing the connection" section from the OpenSearch resource article.
=> Remove empty testing section

CHANGELOG.md, Makefile, api/v1alpha1/userconfigs/cassandra/cassandra.go, api/v1alpha1/userconfigs/grafana/grafana.go, api/v1alpha1/userconfigs/kafka/kafka.go, api/v1alpha1/userconfigs/kafka_connect/kafka_connect.go, api/v1alpha1/userconfigs/mysql/mysql.go, api/v1alpha1/userconfigs/opensearch/opensearch.go, api/v1alpha1/userconfigs/pg/pg.go, api/v1alpha1/userconfigs/redis/redis.go, config/crd/bases/aiven.io_cassandras.yaml, config/crd/bases/aiven.io_kafkas.yaml, config/crd/bases/aiven.io_mysqls.yaml, config/crd/bases/aiven.io_opensearches.yaml, config/crd/bases/aiven.io_postgresqls.yaml, controllers/postgresql_controller_test.go, docs/docs/changelog.md, docs/docs/contributing/developer-guide.md, docs/mkdocs.yml, userconfigs_generator/generator.go, userconfigs_generator/generator_test.go, userconfigs_generator/pg/pg.go
YAML validator validates string enums with integer values only as integers. For instance, postgres version `14` is validated as int and can't pass the validation. That makes impossible to set values to that kind of fields.
=> fix(userconfig): string enums parsed as int

docs/docs/installation/helm.md, docs/docs/resources/kafka/connect.md, docs/docs/resources/kafka/index.md, docs/docs/resources/kafka/schema.md, docs/docs/resources/opensearch.md, docs/docs/resources/postgresql.md, docs/docs/resources/project-vpc.md, docs/docs/resources/project.md, docs/docs/resources/redis.md, docs/docs/resources/service-integrations.md, docs/docs/troubleshooting.md
Split up the input and output for console and removed the copy option for outputs. Also replaced a couple of outdated links.
=> Split console inputs and output examples in docs

controllers/kafkatopic_controller.go, controllers/kafkatopic_controller_test.go
Hello, I bumped aiven-operator to 0.8.0 in our test cluster and tried to set: 
`apiVersion: aiven.io/v1alpha1
kind: KafkaTopic
metadata:
name: aiven-kafka-topic
namespace: kafka-sandbox
spec:
authSecretRef:
name: aiven-token
key: token
config:
min_cleanable_dirty_ratio: 0.2
termination_protection: false
project: some-aiven-project
serviceName: aiven-kafka-sandbox
partitions: 1
replication: 2⏎`
Aiven-Operator accepted the manifest but min_cleanable_dirty_ratio set was not reflected in Aiven console. There it was  set to 0.5 with source: "Kafka Default Configuration". 
I checked the commit and the MinCleanableDirtyRatio was missing from convertKafkaTopicConfig used in create/update func. Also if the tests is a full integration test running against some Aiven service using 0.5 as the test …
=> [bug]Setting config: min_cleanable_dirty_ratio: 0.1 does not apply

go.mod, go.sum
The go-client is broken on my box and it is not latest as well.
=> chore: update to the latest go-client

CHANGELOG.md, api/v1alpha1/userconfig/service/cassandra/cassandra.go, api/v1alpha1/userconfig/service/clickhouse/clickhouse.go, api/v1alpha1/userconfig/service/grafana/grafana.go, api/v1alpha1/userconfig/service/kafka/kafka.go, api/v1alpha1/userconfig/service/kafka_connect/kafka_connect.go, api/v1alpha1/userconfig/service/mysql/mysql.go, api/v1alpha1/userconfig/service/opensearch/opensearch.go, api/v1alpha1/userconfig/service/pg/pg.go, api/v1alpha1/userconfig/service/redis/redis.go, generators/userconfigs/generator.go, generators/userconfigs/generator_test.go, generators/userconfigs/pg/pg.go
Ip filter objects introduced in v0.8.0.
Since we had some breaking changes there, this compatibility layer doesn't help at all.
=> refactor(ip_filter): remove backward compatibility

CHANGELOG.md, controllers/basic_controller.go, controllers/common.go
Some errors, like termination protection, has been omitted.
This fix creates warning event with the omitted error.
=> fix(delete): deletion errors omitted

CHANGELOG.md, charts/aiven-operator/templates/cluster_role.yaml, charts/aiven-operator/templates/cluster_role_binding.yaml, charts/aiven-operator/values.yaml
This change allows the Helm chart be installed without including the creation of cluster-wide resources (ClusterRoles/ClusterRoleBindings). Specifically, this change supports at least 2 use cases:
1. The scenario where the engineer installing the chart has limited (i.e. namespace only) access and cannot install cluster-wide resources. This change allows the cluster-wide resources to be installed separately by cluster administrators while still allowing the engineers to manage the operator itself without having full cluster-wide access.
2. The scenario where the operator only needs to manage resources in a specific namespace and not the entire cluster.
I believe this is the first pull request into this repository since moving the Aiven charts from its [dedicated …
=> feat: add rbac options to helm chart

.github/dependabot.yml, CHANGELOG.md, charts/aiven-operator/templates/cluster_role.yaml, charts/aiven-operator/templates/cluster_role_binding.yaml, config/rbac/role.yaml, config/samples/aiven.io_v1alpha1_kafka.yaml, controllers/clickhouseuser_controller.go, controllers/connectionpool_controller.go, controllers/kafka_controller.go, controllers/kafkaconnect_controller.go, controllers/kafkaconnector_controller.go, controllers/opensearch_controller.go, controllers/postgresql_controller.go, controllers/project_controller.go, controllers/redis_controller.go, controllers/serviceuser_controller.go, docs/docs/api-reference/examples/kafka.yaml, docs/docs/api-reference/kafka.md, generators/charts/cluster_roles.go, test/e2e/kafka-topic/simple-kafka-topic/01-kafka.yaml, test/e2e/kafka/kafka-simple-cluster/01-kafka.yaml
- Fixes error `cannot set blockOwnerDeletion if an ownerReference refers to a resource you can’t set finalizers on`. Covered in Operator SDK [FAQ](https://sdk.operatorframework.io/docs/faqs/#after-deploying-my-operator-why-do-i-see-errors-like-is-forbidden-cannot-set-blockownerdeletion-if-an-ownerreference-refers-to-a-resource-you-cant-set-finalizers-on-)
- Fixes kuttle tests
- Fixes dependabot config for k8s libs
=> fix(charts): add required RBAC permissions to update finalizers

CHANGELOG.md, api/v1alpha1/serviceintegration_types.go, charts/aiven-operator-crds/templates/aiven.io_serviceintegrations.yaml, config/crd/bases/aiven.io_serviceintegrations.yaml, docs/docs/api-reference/serviceintegration.md, go.mod, go.sum
- Removes deprecated service integration type `signalfx`
- Bumps up `go-api-schemas` version
=> chore(service_integration): remove signalfx type

Makefile, docs/docs/contributing/developer-guide.md, test/e2e/kuttl-test.preinstalled.yaml
=> test(charts): install in kind

charts/aiven-operator/Chart.yaml, charts/aiven-operator/templates/ensure_cert_manager_if_webhooks_are_enabled.yaml, charts/aiven-operator/values.yaml
Kustomize does not play nicely with helm .Capabilities as it doesn't currently let you pass those values.
See: https://github.com/kubernetes-sigs/kustomize/issues/4256
This just allows to disable the capability check. Still enabled by default.
=> feat(chart): allow to disable helm capabilities check

Makefile, tests/suite.go
- Fixes test suite concurrent map access by making resource deletion idempotent. "not found" error ignored, which may occur if resource deleted manually. 
- Test resources have to have unique names now, as objects get ID after they applied only, and that requires additional logic on delete. Especially when it panicked.
- Runs tests with race flag to detect race conditions
- Recovers panics in goroutines
=> fix(tests): concurrent map access

.github/workflows/release.yaml
run `sync-charts` as a last step in `release` workflow
=> ci(release): sync charts as last step

tests/cassandra_test.go, tests/clickhouse_test.go, tests/clickhouseuser_test.go, tests/connectionpool_test.go, tests/database_test.go, tests/grafana_test.go, tests/kafka_test.go, tests/kafka_with_projectvpc_ref_test.go, tests/kafkaacl_test.go, tests/kafkaconnect_test.go, tests/kafkaschema_test.go, tests/kafkatopic_test.go, tests/mysql_test.go, tests/opensearch_test.go, tests/postgresql_test.go, tests/projectvpc_test.go, tests/redis_test.go, tests/serviceintegration_test.go, tests/serviceuser_test.go, tests/suite_test.go
This allows for using other cloud providers in cases where GCP has problems, like the case was today.
=> Allow overriding cloudName used in tests

CHANGELOG.md, charts/aiven-operator/templates/cluster_role.yaml, charts/aiven-operator/templates/cluster_role_binding.yaml, charts/aiven-operator/values.yaml, docs/docs/installation/helm.md
This change allows the Helm chart be installed without including the creation of cluster-wide resources (ClusterRoles/ClusterRoleBindings). Specifically, this change supports the use case where the engineer installing the chart has limited (i.e. namespace only) access and cannot install cluster-wide resources. This change allows the cluster-wide resources to be installed separately by cluster administrators while still allowing the engineers to manage the operator itself without having full cluster-wide access.
It is understood that if `clusterRole.create=false` is set without the cluster role/cluster role binding being installed beforehand the operator will not function as expected but this gives the option to have the namespaced resources installed/managed by individuals with …
=> feat: allow optional installation of cluster role

api/v1alpha1/common.go, charts/aiven-operator-crds/templates/aiven.io_cassandras.yaml, charts/aiven-operator-crds/templates/aiven.io_clickhouses.yaml, charts/aiven-operator-crds/templates/aiven.io_grafanas.yaml, charts/aiven-operator-crds/templates/aiven.io_kafkaconnects.yaml, charts/aiven-operator-crds/templates/aiven.io_kafkas.yaml, charts/aiven-operator-crds/templates/aiven.io_mysqls.yaml, charts/aiven-operator-crds/templates/aiven.io_opensearches.yaml, charts/aiven-operator-crds/templates/aiven.io_postgresqls.yaml, charts/aiven-operator-crds/templates/aiven.io_redis.yaml, config/crd/bases/aiven.io_cassandras.yaml, config/crd/bases/aiven.io_clickhouses.yaml, config/crd/bases/aiven.io_grafanas.yaml, config/crd/bases/aiven.io_kafkaconnects.yaml, config/crd/bases/aiven.io_kafkas.yaml, config/crd/bases/aiven.io_mysqls.yaml, config/crd/bases/aiven.io_opensearches.yaml, config/crd/bases/aiven.io_postgresqls.yaml, config/crd/bases/aiven.io_redis.yaml
In some cases, the someone might attempt to pass an object with a `status` attribute, but with no `conditions` or `state`.
When attempting to read such objects you may encounter errors about the missing attributes.
When marking them with `omitempty`, the generated schema will no longer consider these attributes required, which probably is more correct, and allows parsers to correctly parse these objects.
=> fix: make conditions and state optional attributes of service status

CHANGELOG.md, api/v1alpha1/kafka_types.go, charts/aiven-operator-crds/templates/aiven.io_kafkas.yaml, config/crd/bases/aiven.io_kafkas.yaml, controllers/kafka_controller.go, docs/docs/api-reference/kafka.md, tests/kafka_test.go
Hey @byashimov
Thanks for the [PR](https://github.com/aiven/aiven-operator/issues/425) earlier for the SASL stuff, I noticed some more components are missing.
So, not to bother you I just created a PR but I could not verify the tests locally.
The ones I added are just the components we are using now, I don't know if there are any more on your platform.
I guess someone needs to clean this up, but it's a start for now.
=> feat(kafka): expose component ports

CHANGELOG.md, api/v1alpha1/kafka_types.go, charts/aiven-operator-crds/templates/aiven.io_kafkas.yaml, config/crd/bases/aiven.io_kafkas.yaml, controllers/kafka_controller.go, docs/docs/api-reference/kafka.md, tests/kafka_test.go
Requires integration endpoint support. Related to #439
=> fix(kafka): remove prometheus port expose

controllers/basic_controller.go
Fixes resource deletion even with expired or missing token.
=> fix: finalize non-running service with expired token

tests/project_test.go
Fails with "project with an open balance cannot be deleted" error. To run the test one need to emulate a payment.
=> chore(project): skip the project test

CHANGELOG.md, docs/docs/changelog.md, docs/mkdocs.yml, generators/charts/changelog.go, generators/charts/changelog_test.go
=> fix(docs): use pymdownx.tilde extension to render deleted content

controllers/basic_controller.go, controllers/common.go, controllers/connectionpool_controller.go, controllers/database_controller.go, controllers/generic_service_handler.go, controllers/kafkaacl_controller.go, controllers/kafkaconnector_controller.go, controllers/kafkatopic_controller.go, controllers/project_controller.go
We are using aiven-operator in an argocd-setup where we heavily rely on status conditions for synchronization and monitoring purposes. After evaulating the operator we found two major issues:
- In the case of failed preconditions, actual conditions never get written to kube-api
- In the case of error, no condition is ever set on kube-api level to indicate that something failed
Changes this PR introduces:
1. defer function was moved to a higher level in order to consistently trigger status-updates
2. new status conditions in the case of an error during find, create, update, delete were added
3. a new event was introduced sent out when preconditions are not met
This pr builds on top of some of the work done in https://github.com/aiven/aiven-operator/pull/101
I was reading the full …
=> feat: implement error-conditions

docs/docs/installation/helm.md, docs/docs/installation/kubectl.md
Add a link to the prerequisites list to both sets of installation instructions to make sure customers are aware of what they need before installing.
=> docs: link to prereqs from installation instructions

CHANGELOG.md, Makefile, api/v1alpha1/userconfig/service/kafka/zz_generated.deepcopy.go, controllers/basic_controller.go, controllers/clickhouseuser_controller.go, controllers/common.go, controllers/connectionpool_controller.go, controllers/database_controller.go, controllers/generic_service_handler.go, controllers/kafkaacl_controller.go, controllers/kafkaconnector_controller.go, controllers/kafkatopic_controller.go, controllers/project_controller.go, go.mod, go.sum, tests/generic_service_handler_test.go
This PR:
- fixes object updates lose during reconciliation
- sets error conditions on basic controller level
=> fix(controllers): object not committed properly

CHANGELOG.md, charts/aiven-operator-crds/Chart.yaml, charts/aiven-operator/Chart.yaml, docs/docs/changelog.md
Changes [v0.15.0...main](https://github.com/aiven/aiven-operator/compare/v0.15.0...main)
=> chore(release): v0.16.0

CHANGELOG.md, controllers/kafka_controller.go, tests/kafka_test.go
Expose `KAFKA_SCHEMA_REGISTRY_URI` and `KAFKA_REST_URI` to `Kafka` secret. Resolves #562
=> feat(kafka): expose schema registry and rest uris

CHANGELOG.md, api/v1alpha1/connectionpool_types.go, charts/aiven-operator-crds/templates/aiven.io_connectionpools.yaml, config/crd/bases/aiven.io_connectionpools.yaml, controllers/connectionpool_controller.go, docs/docs/api-reference/connectionpool.md, tests/connectionpool_test.go
- Exposes `CONNECTIONPOOL_NAME`. Resolves #560 
- Fixes `CONNECTIONPOOL_PORT` has invalid port value (the one from the service)
=> feat(connection_pool): expose pool name

CHANGELOG.md, Makefile, controllers/serviceuser_controller.go, tests/serviceuser_test.go
=> fix(serviceuser): expose different port when sasl enabled

Makefile
If `goimports` wasn't installed, `make build` would fail with:
❯ make build
go generate ./...
2023/12/18 11:45:04 can't compile field "topic_name" regex `^(?!\.$|\.\.$)[-_.A-Za-z0-9]+$`: error parsing regexp: invalid or unsupported Perl syntax: `(?!`
2023/12/18 11:45:04 can't compile field "name" regex `^(?!\.$|\.\.$)[-_.A-Za-z0-9]+$`: error parsing regexp: invalid or unsupported Perl syntax: `(?!`
2023/12/18 11:45:04 can't compile field "tag" regex `^(?!aiven-)[^\W\d_](?:[:\w./-]*[\w./-])?$`: error parsing regexp: invalid or unsupported Perl syntax: `(?!`
2023/12/18 11:45:04 can't compile field "kafka_topic" regex `^(?!\.$|\.\.$)[-_.A-Za-z0-9]+$`: error parsing regexp: invalid or unsupported Perl syntax: `(?!`
test -s /Users/riski/code/work/aiven-operator/bin/controller-gen || …
=> fix(makefile): install `goimports` to $(LOCALBIN)

README.md, docs/docs/contributing/developer-guide.md, docs/docs/resources/cassandra.md, docs/docs/resources/kafka/index.md, docs/docs/resources/mysql.md, docs/docs/resources/opensearch.md, docs/docs/resources/postgresql.md, docs/docs/resources/redis.md
jq repo has moved from `stedolan` to `jqlang` https://github.com/jqlang/jq/issues/2305#issuecomment-1572634869.
=> fix(docs): update `jq` repo links

.github/workflows/lint.yml, .github/workflows/release.yml, Makefile
* Align tool installation with kubebuilder v4 template: https://github.com/kubernetes-sigs/kubebuilder/blob/165af70e87848677a039cd0cd87cc67c545d983c/testdata/project-v4/Makefile
* Remove `goimports` target, it was added in https://github.com/aiven/aiven-operator/commit/5cc56e2bfe0c7155e0cab2c419791e52b46904ce by me. As its not a versioned dependency, and it is very commonly used, we can expect that people familiar with go either a) already have it or b) know how to install it
* Update kustomize to v4.5.7 to align with their versioning policy: https://github.com/kubernetes-sigs/kustomize?tab=readme-ov-file#kubectl-integration (kubectl v4.5.7 is compatible with k8s v1.26)
* Install kubebuilder asset in `envtest` target. This makes it easier to setup IDE integrations to point to the correct …
=> feat(makefile): improve tool installation and kubebuilder asset installation process

tests/service_opts_test.go
Max length for Aiven service names is 64 characters
=> fix(tests): shorter service names in connection secret tests

.github/workflows/trunk-upgrade.yml
https://github.com/aiven/aiven-operator/pull/595 failed in CI and upstream changes were required and done in https://github.com/trunk-io/trunk-action/pull/218.
=> ci: add options to pass commitlint to trunk-upgrade action

.github/workflows/lint.yml
adds setup Go step to codeql workflow
=> ci(codeql): add setup Go step

tests/session.go, tests/suite_test.go
This addresses an issue that has been failing any commit that occurred after #632
=> fix(tests): move defaultNamespace const to fix undefined variable issue

tests/projectvpc_test.go, tests/session.go
To better understand what exactly failed, `retryForever` now requires that a string that contains a description of the operation be passed.
=> feat(tests): log operation status when calling `retryForever`

go.mod, tests/cassandra_test.go, tests/clickhouse_test.go, tests/clickhouseuser_test.go, tests/connectionpool_test.go, tests/database_test.go, tests/generic_service_handler_test.go, tests/grafana_test.go, tests/kafka_test.go, tests/kafka_with_projectvpc_ref_test.go, tests/kafkaacl_test.go, tests/kafkaconnect_test.go, tests/kafkaschema_test.go, tests/kafkatopic_test.go, tests/mysql_test.go, tests/opensearch_test.go, tests/postgresql_test.go, tests/project_test.go, tests/projectvpc_test.go, tests/redis_test.go, tests/service_opts_test.go, tests/serviceintegration_test.go, tests/serviceuser_test.go, tests/session.go, tests/suite_test.go
1. Unifies tests configuration by using envconfig, replaces individual per-var validations
2. Removes testEnv global variable
3. Fixes kafka topic test
=> refactor(tests): use envconfig for configuration

.github/workflows/tests.yml, Makefile, sweeper/main.go, sweeper/service_integrations.go, sweeper/services.go, sweeper/vpcs.go
Adds `sweep` target to Makefile, which will run a sweeper to delete resources in a project. This would include:
- services that have "test-" as a prefix for their name
- service integration endpoints
- VPCs
=> ci(tests): add sweeper to destroy resources after test runs

.github/workflows/tests.yml, Makefile, tests/cassandra_test.go, tests/clickhouse_test.go, tests/clickhouseuser_test.go, tests/connectionpool_test.go, tests/database_test.go, tests/generic_service_handler_test.go, tests/grafana_test.go, tests/kafka_test.go, tests/kafka_with_projectvpc_ref_test.go, tests/kafkaacl_test.go, tests/kafkaconnect_test.go, tests/kafkaschema_test.go, tests/kafkatopic_test.go, tests/mysql_test.go, tests/opensearch_test.go, tests/postgresql_test.go, tests/project_test.go, tests/projectvpc_test.go, tests/redis_test.go, tests/service_opts_test.go, tests/serviceintegration_test.go, tests/serviceuser_test.go, tests/session.go, tests/suite_test.go
- Tries to destroy resources even when panics
- Splits tests into separate jobs, as individual timeouts are not supported in go [yet](https://github.com/golang/go/issues/48157)
- Adds per-test context timeout to end test gracefully
- Increases the test runner timeout to 30 minutes to let timeouting test finish
=> ci(tests): fix tests panic

controllers/basic_controller.go, controllers/clickhouseuser_controller.go, controllers/common.go, controllers/connectionpool_controller.go, controllers/database_controller.go, controllers/generic_service_handler.go, controllers/kafkaacl_controller.go, controllers/kafkaconnector_controller.go, controllers/kafkaschema_controller.go, controllers/kafkatopic_controller.go, controllers/project_controller.go, controllers/projectvpc_controller.go, controllers/serviceuser_controller.go
Now we are mixing the old and the new client. Error checks must support both types of errors: the old and the new one.
=> refactor: use compatible client error checks

.github/workflows/release.yml
Fixes incorrect release branch in `release.yml`. Because the change is triggered by a tag, `github.ref_name` contains the name of the tag, e.g. `v0.17.0`, `v0.18.0`, etc.
=> ci(release): fix incorrect release branch

controllers/common.go, tests/kafkatopic_test.go, tests/session.go
- Fixes kafka topic test
- Fails tests on error condition
=> chore(tests): fix kafka topic invalid test

CHANGELOG.md, docs/docs/changelog.md
Must include the kube version gathering change.
=> docs(changelog): add missing user-agent entry

.github/dependabot.yml, .github/workflows/lint.yml, commitlint.config.js
Reverts aiven/aiven-operator#690
This breaks the ability to run `commitlint` locally when committing.
=> Revert "build(deps): bump wagoid/commitlint-github-action from 5 to 6"

docs/docs/installation/helm.md, docs/docs/installation/prerequisites.md, docs/docs/resources/cassandra.md, docs/docs/resources/kafka/index.md, docs/docs/resources/opensearch.md, docs/docs/resources/postgresql.md, docs/docs/resources/project-vpc.md, docs/docs/resources/project.md, docs/docs/resources/redis.md, docs/docs/resources/service-integrations.md
There was missing indentation on several admonitions which resulted in a admonition box (e.g. 'Note') and the text that should be inside the box was just appearing below the box as regular text.
Fix:
After a '!!! note' etc. the admonition content on the next line need to be aligned with the 'note'.
=> fix(docs): indentation formatting on several admonitions

tests/suite_test.go
current user-agent during tests is:
`k8s-operator/x.y.z-test/test-test`
where `x.y.z` is the k8s version
this PR uniforms it with what we use in Terraform: `terraform-provider-aiven/x.y.z/test`, i.e. it'll be `k8s-operator/x.y.z/test`
=> test: uniform user-agent

CHANGELOG.md, controllers/common.go
unifies User-Agent format with the one used in Terraform
=> chore: unified user-agent format

.github/dependabot.yml, .github/workflows/lint.yml, commitlint.config.mjs
We run commitlint locally via trunk, but trunk-action doesn't run commitlint in CI so we still need `wagoid/commitlint-github-action`.
=> chore(ci): update commitlint config to v19 format and update commitlint-github-action

CHANGELOG.md, controllers/serviceintegration_controller.go, controllers/serviceintegrationendpoint_controller.go
`ServiceIntegration` instance without id is looped in deletion.
The bug appeared in [017d5c5:133](https://github.com/aiven/aiven-operator/commit/017d5c54d8023a9feff324fd970815e97440f56f#diff-964ab155d891c32d1b45aff877417feae4cdc021214efe999f94e0e409c750a1R133) and [017d5c5:137](https://github.com/aiven/aiven-operator/commit/017d5c54d8023a9feff324fd970815e97440f56f#diff-964ab155d891c32d1b45aff877417feae4cdc021214efe999f94e0e409c750a1R137) after refactoring and copy-pasted to the service integration endpoint controller later. Before that, deletion was requested with empty id which produced false positive 404, yet it worked.
While `ServiceIntegrationEndpoint` is not released yet, not mentioning it in the changelog.
=> fix(serviceintegration): skip delete if has no id

tests/session.go
Sets delete timeout so test fails before it panics.
=> fix(tests): set delete timeout

CHANGELOG.md, api/v1alpha1/clickhouse_types.go, api/v1alpha1/grafana_types.go, api/v1alpha1/opensearch_types.go, charts/aiven-operator-crds/templates/aiven.io_clickhouses.yaml, charts/aiven-operator-crds/templates/aiven.io_grafanas.yaml, charts/aiven-operator-crds/templates/aiven.io_opensearches.yaml, config/crd/bases/aiven.io_clickhouses.yaml, config/crd/bases/aiven.io_grafanas.yaml, config/crd/bases/aiven.io_opensearches.yaml, controllers/generic_service_handler.go, docs/docs/api-reference/clickhouse.md, docs/docs/api-reference/grafana.md, docs/docs/api-reference/opensearch.md, tests/clickhouse_test.go, tests/grafana_test.go, tests/opensearch_test.go
Removes redundant CA_CERT secret key for `Grafana`, `OpenSearch`, and `Clickhouse`. Can't be used with these service types
=> fix: remove redundant CA_CERT secret key

.github/workflows/lint.yml, .github/workflows/release.yml
Lint action was failing consistently with:
```bash
curl: option : blank argument where content is expected
curl: try 'curl --help' or 'curl --manual' for more information
```
See: 
- https://github.com/aiven/aiven-operator/actions/runs/9386573825/job/25847480037?pr=745.
- https://github.com/karancode/kustomize-github-action/issues/46#issuecomment-2136079824
=> fix(ci): add `token` to kustomize-github-action

api/v1alpha1/clickhousedatabase_types.go, api/v1alpha1/clickhouserole_types.go, api/v1alpha1/clickhouseuser_types.go, charts/aiven-operator-crds/templates/aiven.io_clickhousedatabases.yaml, charts/aiven-operator-crds/templates/aiven.io_clickhouseroles.yaml, charts/aiven-operator-crds/templates/aiven.io_clickhouseusers.yaml, config/crd/bases/aiven.io_clickhousedatabases.yaml, config/crd/bases/aiven.io_clickhouseroles.yaml, config/crd/bases/aiven.io_clickhouseusers.yaml, controllers/clickhousedatabase_controller.go, controllers/clickhouserole_controller.go, controllers/clickhouseuser_controller.go, docs/docs/api-reference/clickhouse.md, docs/docs/api-reference/clickhousedatabase.md, docs/docs/api-reference/clickhouserole.md, docs/docs/api-reference/clickhouseuser.md, docs/docs/api-reference/examples/clickhouse.yaml, docs/docs/api-reference/examples/clickhousedatabase.yaml, docs/docs/api-reference/examples/clickhouserole.yaml, docs/docs/api-reference/examples/clickhouseuser.yaml, tests/clickhouse_test.go, tests/clickhouseuser_test.go
Previously the username was set from Metadata.name, which doesn't support UTF-8:
The ClickhouseUser "testuser-🦄" is invalid: metadata.name: Invalid
value: "testuser-🦄": a lowercase RFC 1123
Clickhouse usernames have UTF-8 support. This can be verified by running:
CREATE USER 'testuser-🦄' IDENTIFIED BY 'testpassword'
=> feat(clickhouseuser,clickhousedatabase): support UTF-8 names for user and database names

docs/docs/api-reference/cassandra.md, docs/docs/api-reference/clickhouse.md, docs/docs/api-reference/clickhouseuser.md, docs/docs/api-reference/grafana.md, docs/docs/api-reference/kafka.md, docs/docs/api-reference/mysql.md, docs/docs/api-reference/opensearch.md, docs/docs/api-reference/postgresql.md, docs/docs/api-reference/project.md, docs/docs/api-reference/redis.md, docs/docs/api-reference/serviceuser.md, generators/docs/generator.go
Generets kubectl secret commands and examples.
=> docs: generate secret commands

CHANGELOG.md, controllers/clickhousegrant_controller.go, controllers/clickhouserole_controller.go, controllers/common.go
Ignore `ClickhouseRole`, `ClickhouseGrant` deletion errors
=> fix(clickhouserole): ignore deletion errors

docs/docs/api-reference/cassandra.md, docs/docs/api-reference/clickhouse.md, docs/docs/api-reference/clickhousedatabase.md, docs/docs/api-reference/clickhousegrant.md, docs/docs/api-reference/clickhouserole.md, docs/docs/api-reference/clickhouseuser.md, docs/docs/api-reference/connectionpool.md, docs/docs/api-reference/database.md, docs/docs/api-reference/grafana.md, docs/docs/api-reference/kafka.md, docs/docs/api-reference/kafkaacl.md, docs/docs/api-reference/kafkaconnect.md, docs/docs/api-reference/kafkaschema.md, docs/docs/api-reference/kafkaschemaregistryacl.md, docs/docs/api-reference/kafkatopic.md, docs/docs/api-reference/mysql.md, docs/docs/api-reference/opensearch.md, docs/docs/api-reference/postgresql.md, docs/docs/api-reference/project.md, docs/docs/api-reference/projectvpc.md, docs/docs/api-reference/redis.md, docs/docs/api-reference/serviceintegration.md, docs/docs/api-reference/serviceintegrationendpoint.md, docs/docs/api-reference/serviceuser.md, docs/docs/authentication.md, generators/docs/generator.go
The [authentication](https://aiven.github.io/aiven-operator/authentication.html) page is quite hard to find. Better put it right before example instructions.
=> docs: add secret dependency warning

.github/workflows/tests.yml, CHANGELOG.md, controllers/generic_service_handler.go, tests/kafkschemaregistryaacl_test.go
Fixes ["No valid backups for service"](https://github.com/aiven/aiven-operator/actions/runs/9940577849/job/27459035954#step:4:31) error.
=> fix(postgresql): no valid backups for read replica

controllers/clickhousedatabase_controller.go, controllers/clickhousegrant_controller.go, controllers/clickhouserole_controller.go, controllers/clickhouseuser_controller.go, controllers/common.go, controllers/connectionpool_controller.go, controllers/database_controller.go, controllers/generic_service_handler.go, controllers/kafkaacl_controller.go, controllers/kafkaconnector_controller.go, controllers/kafkaschema_controller.go, controllers/kafkaschemaregistryacl_controller.go, controllers/serviceintegration_controller.go, controllers/serviceuser_controller.go
No need to have it anymore in `checkServiceIsOperational`.
=> refactor: use gen client to check service is operational

tests/postgresql_test.go
Don't test against the latest version, it may not be supported yet by the operator
=> fix: pg upgrade check test

go.mod, go.sum, tests/serviceintegration_test.go, tests/serviceintegrationendpoint_test.go
Request secrets in `ServiceIntegrationEndointGet` calls
=> feat: add `include_secrets` query param to `ServiceIntegrationEndointGet` calls

api/v1alpha1/serviceintegration_types.go, controllers/serviceintegration_controller.go, controllers/serviceintegrationendpoint_controller.go, go.mod, go.sum, tests/serviceintegrationendpoint_test.go, tests/session.go
Uses upcoming changes https://github.com/aiven/go-client-codegen/pull/131
=> chore: uses service module from the gen client

CHANGELOG.md, api/v1alpha1/kafkaschema_types.go, charts/aiven-operator-crds/templates/aiven.io_kafkaschemas.yaml, config/crd/bases/aiven.io_kafkaschemas.yaml, controllers/kafkaschema_controller.go, docs/docs/api-reference/kafkaschema.md, go.mod, go.sum, tests/kafkaschema_test.go
- Fix `KafkaSchema`: poll resource availability
- Add `KafkaSchema` field `schemaType`, type `string`: Schema type
Resolves #800
=> fix(kafkaschema): poll 404

tests/cassandra_test.go, tests/kafka_test.go, tests/mysql_test.go, tests/opensearch_test.go, tests/serviceintegration_test.go
Fixes broken tests, see e.g. this run https://github.com/aiven/aiven-operator/actions/runs/11564675507
=> fix: tests broken after go-client-codegen updates

Makefile
The current command looks for `'s/"[\r\n\t]\+"/"\n"/g'`— newlines and tabs before `"`. Hence, fails to sort lines with aliases: `\n\tmymodule"`.
=> fix: make fmt-imports

charts/aiven-operator/templates/cluster_role.yaml
Release v0.27.0
Somehow valkey was incorrectly named in `charts/`. Running `make charts` made the changes.
=> chore(release): v0.27.0

generators/charts/changelog.go, generators/charts/cluster_roles.go, generators/charts/utils.go, generators/charts/version.go, generators/docs/generator.go, generators/docs/validator.go, generators/userconfigs/generator.go, generators/userconfigs/generator_test.go, go.mod, go.sum
Uses `yaml` lib to split schemas.
=> fix(docs): do not split schemas manually

generators/docs/generator.go, go.mod
`goccy/go-yaml` broke docs example generation due to some incompatability
=> fix: docs example generation

docs/docs/resources/clickhouse.md, docs/docs/resources/kafka/index.md, docs/docs/resources/mysql.md, docs/docs/resources/opensearch.md, docs/docs/resources/postgresql.md, docs/docs/resources/project-vpc.md, docs/docs/resources/project.md, docs/docs/resources/redis.md, docs/docs/resources/service-integrations.md
Adds EOL notice to Redis resource and updates language in API reference notice. Also replaces note callouts
across all docs with a prerequisites section
to make notices like this EOL callout more prominent.
=> docs(redis): add EOL notice to Redis resource [DOC-1302]

docs/docs/resources/alloydbomni.md, docs/docs/resources/cassandra.md, docs/docs/resources/clickhouse.md, docs/docs/resources/clickhousedatabase.md, docs/docs/resources/clickhousegrant.md, docs/docs/resources/clickhouserole.md, docs/docs/resources/clickhouseuser.md, docs/docs/resources/connectionpool.md, docs/docs/resources/database.md, docs/docs/resources/flink.md, docs/docs/resources/grafana.md, docs/docs/resources/kafka.md, docs/docs/resources/kafkaacl.md, docs/docs/resources/kafkaconnect.md, docs/docs/resources/kafkaschema.md, docs/docs/resources/kafkaschemaregistryacl.md, docs/docs/resources/kafkatopic.md, docs/docs/resources/mysql.md, docs/docs/resources/opensearch.md, docs/docs/resources/postgresql.md, docs/docs/resources/project.md, docs/docs/resources/projectvpc.md, docs/docs/resources/redis.md, docs/docs/resources/serviceintegration.md, docs/docs/resources/serviceintegrationendpoint.md, docs/docs/resources/serviceuser.md, docs/docs/resources/valkey.md, docs/mkdocs.yml, generators/docs/generator.go
Expandable blocks reduce text size making code snippets hard to read.
- Removes expandable blocks
- Uses tabs to display multiple examples
=> docs: use tabs for code snippets

CHANGELOG.md, controllers/kafkatopic_controller.go
Better handle API 5xx errors for `KafkaTopic`.
- Do not check if topic exists, just create it, and update on "conflict"
- Retry all 5xx errors in `checkPreconditions()`
Resolves NEX-1609.
=> refactor(kafkatopic): better handle 5xx errors

CHANGELOG.md, controllers/kafkaconnector_controller.go
Resolves NEX-1610.
- Doesn't call `ServiceKafkaConnectGetConnectorStatus` to know if the connector exists. 
It might return OK, and `ServiceKafkaConnectCreateConnector` might fail with 404 right after. Instead calls "create", and `ServiceKafkaConnectEditConnector` to update it if gets a conflict.
- Additionally, retries all 5xx errors.
=> fix(kafkaconnector): better handle api errors

.github/workflows/lint.yml, Taskfile.dist.yml, Taskfile.internal.yml, controllers/generic_service_handler.go
- Adds a linting step to the lint workflow.
- Adds a new task `lint:go` that doesn't run the `trunk`: ci uses `trunk-io/trunk-action@v1` action.
=> ci: run `task lint:go` on push

tests/connectionpool_test.go
Fixes: NEX-747
- use proper secret keys in ConnectionPool tests
=> fix: fixed ConnectionPool tests to use proper secret keys

CHANGELOG.md, controllers/basic_controller.go, controllers/clickhousedatabase_controller.go, controllers/clickhousegrant_controller.go, controllers/clickhouserole_controller.go, controllers/clickhouseuser_controller.go, controllers/connectionpool_controller.go, controllers/database_controller.go, controllers/generic_service_handler.go, controllers/kafkaacl_controller.go, controllers/kafkaconnector_controller.go, controllers/kafkanativeacl_controller.go, controllers/kafkaschema_controller.go, controllers/kafkaschemaregistryacl_controller.go, controllers/kafkatopic_controller.go, controllers/project_controller.go, controllers/projectvpc_controller.go, controllers/serviceintegration_controller.go, controllers/serviceintegrationendpoint_controller.go, controllers/serviceuser_controller.go
Resolves NEX-1670.
Consolidates status conditions `Create` and `Update` into `CreateOrUpdate` due to limitations in reliably determining operation type.
1. The go client's retry mechanism may create an instance successfully but receive a 5xx error,
causing the next attempt to get a conflict error
2. Remote state may be temporarily inconsistent, so GET checks can return false positives/negatives
3. Some handlers implement their own retry logic and keep trying to create instances until success
Therefore, we can't rely on "exists" checks to determine the operation type.
=> refactor: consolidate status conditions

.github/workflows/tests.yml, charts/aiven-operator/templates/cluster_role.yaml, config/rbac/role.yaml, controllers/secret_watch_controller.go, tests/connectionpool_test.go, tests/serviceuser_test.go, tests/suite_session.go, tests/suite_shared_resources.go
Resolves: NEX-1754
**Problem:**
- race conditions occurred when secret watcher and test session simultaneously updated the same `ServiceUser` resource, causing "the object has been modified" conflicts during testing
**Solution:**
- Secret watcher: Replaced Update() with merge `Patch` for annotation updates to reduce conflicts
- Test session: Switched from Create/Update to server-side apply (client.Apply) to match closer to `kubectl` [apply behavior](https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/apply/apply.go#L557)
=> fix(secret_watcher): replaced the update with patch

controllers/secret_watch_controller.go, docs/docs/resources/examples/clickhouseuser.yaml, tests/clickhousegrant_test.go, tests/clickhouseuser_test.go, tests/clickhouseuser_watcher_test.go, tests/kafkaacl_test.go, tests/kafkaconnector_test.go, tests/kafkatopic_test.go, tests/kafkschemaregistryacl_test.go, tests/serviceuser_test.go, tests/suite_session.go, tests/suite_shared_resources.go
Resolves: NEX-1782
**Problem**:
- `TestClickhouseGrant` and `TestClickhouseGrantExample` both used hardcoded resource name "`writer`" for `ClickhouseRole`
- When running in parallel (t.Parallel()), both tests created resources with identical names in the same Kubernetes cluster
- This caused race conditions where one test would overwrite another's resources
Additionaly:
- In secret watcher patch implementation using more idiomatic `client.MergeFrom()` 
- Fixed conflicts with shared resources in tests
=> fix(tests): resolve parallel test resource conflicts in tests

tests/serviceuser_test.go
Resolves: NEX-1782
- added retry to service user test
=> fix(service_user): added retry to service user test

controllers/basic_controller.go, docs/docs/guides/deletion-policy.md, docs/mkdocs.yml
Resolves: NEX-1877 & #1022 
- added log when `Orphan` policy is detected and will be applied
- only emit deletion events when actually deleting Aiven resources
- added guide for `Orphan` deletion policy
Log entries example for `Orphan` deletion:
> 2025-09-24T11:05:26Z	INFO	kafkatopic-resource	validate delete	{"name": "test-deletion-policy"}
2025-09-24T11:05:26Z	INFO	controllers.KafkaTopic	'Orphan' deletion policy detected - Aiven resource will be preserved on Kubernetes resource deletion	{"kind": "kafkatopic", "name": "default/test-deletion-policy", "annotations": {"controllers.aiven.io/generation-was-processed":"1","controllers.aiven.io/instance-is-running":"true"}}
2025-09-24T11:05:26Z	INFO	controllers.KafkaTopic	Kubernetes resource finalized with orphan policy - Aiven resource …
=> chore: improved orphan deletion description

CHANGELOG.md, controllers/postgresql_controller.go
Resolves: NEX-1932, #1033 
- due to the fact that this code inside the reconciler all static analysis tools that I'm aware of do not catch this error, unfortunately
=> fix(postgres): fixed potential panic in PostgreSQL controller
